### ISSUE TITLE
Create a bugzilla module with a function to get the crash signatures from a bugzilla bug

### ISSUE THREAD

**Issue by marco-c** [marco-c/crashsimilarity#27]
We will need to use the bugzilla bugs to evaluate the results of the tool. Developers manually clustered signatures together, we need to check that our tools clusters the same signatures together.

As a first step, we need a function that gets crash signatures from a bugzilla bug.

Some documentation is at http://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html.
Example query: https://bugzilla.mozilla.org/rest/bug/1308863.

**Comment by ray-pankaj** [comment]
This works in Ubuntu but not osx
