### ISSUE TITLE
Update gensim library and remove unused code

### ISSUE THREAD

**Issue by KirillTim** [marco-c/crashsimilarity#29]
0.13.3 is very old version, 1.0.1 will be used.
New version has tons of improvements and useful features but broke some API, so careful code update needed.

**Comment by KirillTim** [comment]
In Progress

**Comment by whatust** [comment]
I change on my machine to gensim 1.0.1 and only had to change how to access the variable "syn0norm" and "vocab", from model.syn0norm to model.wvsyn0norm and model vocab to model.wv.vocab, lines 121 and 127 from crash_similarity.py.

**Comment by KirillTim** [comment]
Yeah, it is true.
The main part is to rewrite [top_similar_traces](https://github.com/marco-c/crashsimilarity/blob/b2fb88048c5a0e9121e2b1fd813d65358c57d39a/crash_similarity.py#L128) using new library methods

**Comment by marco-c** [comment]
We are using gensim 1.0.1 now.
