### ISSUE TITLE
Run tests on Travis

### ISSUE THREAD

**Issue by marco-c** [marco-c/crashsimilarity#37]

**Comment by mansimarkaur** [comment]
I'd like to work on this. Do we just want to configure Travis for this issue?

**Comment by marco-c** [comment]
Yes, we just need to modify `.travis.yml` to run all the tests under the `tests` directory.
There is already a pull request that is going to fix this though, #45.

**Comment by marco-c** [comment]
@mansimarkaur if you want, you can start to add `python -m unittest discover tests` to .travis.yml; #45 will then change it to use coverage.

**Comment by marco-c** [comment]
(It will be useful, since you are adding tests and we want to make sure they pass on Travis)

**Comment by marco-c** [comment]
Fixed by #52.
