### ISSUE TITLE
Add standard logger for logging instead of print()

### ISSUE THREAD

**Issue by KirillTim** [marco-c/crashsimilarity#40]
@marco-c Do we need https://docs.python.org/3/library/logging.html ?

**Comment by marco-c** [comment]
Souns good to me!

**Comment by aditya-iitd** [comment]
What info should the logger output?

**Comment by marco-c** [comment]
For now, almost everywhere `print` should be replaced by `logger`. In the future, we can add more logging as needed.

**Comment by ibrahimsharaf** [comment]
@aditya-iitd are you still working on this?

**Comment by aditya-iitd** [comment]
Yes, I will create a new pull request very soon!
