### ISSUE TITLE
Make it possible to perform the training and download the data once a day

### ISSUE THREAD

**Issue by marco-c** [marco-c/crashsimilarity#5]
When running the tool twice, training should be performed only the first time (for each day). Otherwise, every time the user uses the tool, maybe multiple times per day, they have to wait a long time to get a result.

**Comment by aditya-iitd** [comment]
Training should be performed once in a day or once in every 24 hours?
eg- if training is done at 1 pm on a specefic day, can training be done at 12 pm the next day?

**Comment by marco-c** [comment]
Whatever is simpler to implement, as it doesn't matter much. So, I suppose once every 24 hours.

**Comment by aditya-iitd** [comment]
What the user wants to add new data and train the model?

**Comment by marco-c** [comment]
We could add an option to override the check. If the user selects this option, the download and training will be performed again.

**Comment by ibrahimsharaf** [comment]
What's the status of this issue?

**Comment by marco-c** [comment]
@aditya-iitd implemented a couple of functions (https://github.com/marco-c/crashsimilarity/blob/bf76144/utils.py#L17 and https://github.com/marco-c/crashsimilarity/blob/bf76144/utils.py#L23), now we need to actually use them to fix this issue.

**Comment by ibrahimsharaf** [comment]
Ok @marco-c, I'll work on it.
