### ISSUE TITLE
get_signatures_from_bug in bugzilla.py should only remove '[', '@' from the beginning of the string and `]` from the end of the string

### ISSUE THREAD

**Issue by marco-c** [marco-c/crashsimilarity#55]
See https://github.com/marco-c/crashsimilarity/pull/54#discussion_r107404704.

**Comment by ray-pankaj** [comment]
How would this '0x0 | idmcchandler7_64.dll@0x238bf' return '@0x0 | idmcchandler7_64.dll@0x238bf'
Why should it add the @?

**Comment by marco-c** [comment]
The `@` right before the address (`0x0`) is part of the signature. We should only remove the first `@` found on the left of the string, but not any other `@`.

**Comment by ray-pankaj** [comment]
is it safe to assume that the signature will begin with '[@' ?

**Comment by marco-c** [comment]
> is it safe to assume that the signature will begin with '[@' ?

The crash signature field on Bugzilla is a bit strange, so we can't assume a signature starts exactly with those characters. E.g. it could start with a space and then `[@`.

**Comment by marco-c** [comment]
Fixed by #56.
