### ISSUE TITLE
Exception in function wmdistance(model, words1, words2, all_distances):

### ISSUE THREAD

**Issue by KirillTim** [marco-c/crashsimilarity#61]
```
crash_similarity.py in top_similar_traces(model, corpus, stack_trace, top)
    191 
    192         doc_words_clean = [w for w in corpus[doc_id].words if w in model]
--> 193         wmd = wmdistance(model, words_to_test_clean, doc_words_clean, all_distances)  # uses cosine distance
    194 
    195         j = bisect.bisect(confirmed_distances, wmd)

/home/kirill/Desktop/crashsimilarity/crash_similarity.py in wmdistance(model, words1, words2, all_distances)
    139     distances = create_distance_matrix(model, dictionary, docset, all_distances)
    140 
--> 141     assert sum(distances) != 0
    142 
    143     return emd(bow1, bow2, distances)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()```

**Comment by KirillTim** [comment]
@whatust could you tell me, please, what is the purpose of assert on line 140 here: https://github.com/marco-c/crashsimilarity/commit/26dbd916329a507525f7521e07bb0b328cf686b8#diff-e1de157e82b328ad1e362ee8b58fd354 ?
There is no such an assert in the original code. moreover this assert break master branch code. It is not OK. Master code should work at every moment of time

**Comment by mansimarkaur** [comment]
I tried refactoring the tests code for the `crash_similarity.py` file, more specifically, the `test_zero_dist_coherence` method and the `assert sum(distances) != 0` was giving an error. Even I wasn't sure why it was needed. It would be great if someone could explain it's importance. Thanks

**Comment by marco-c** [comment]
I think @whatust's intent was to replicate this: https://github.com/RaRe-Technologies/gensim/blob/4f0e2ae/gensim/models/keyedvectors.py#L410

We should modify the code to actually be the same as gensim.

**Comment by KirillTim** [comment]
@whatust @mansimarkaur Just one more thought about tests.
The purpose of unit tests is to make sure that every single function\class\method of important or potentially error prone component works correct. In open source world tests also help contributors to understand whats going on in the project.
Could you please add tests for crucial functions: [create_distance_matrix(..)](https://github.com/marco-c/crashsimilarity/blob/bfe9de32552ea839630845196ea462e03c81bd4e/crash_similarity.py#L111) and [wmdistance(...)](https://github.com/marco-c/crashsimilarity/blob/bfe9de32552ea839630845196ea462e03c81bd4e/crash_similarity.py#L121) ? Some refactoring and bugfixes can be needed too. 
It is not a piece of cake but it will help us to move forward with similarities algorithms and fix master branch.

**Comment by ibrahimsharaf** [comment]
@marco-c are we trying to re-implement the function using cosine distance or euclidean distance like Gensim's code?

**Comment by marco-c** [comment]
> @marco-c are we trying to re-implement the function using cosine distance or euclidean distance like Gensim's code?

Cosine distance

**Comment by ibrahimsharaf** [comment]
WIP

**Comment by marco-c** [comment]
> WIP

Please also add a couple of tests for `wmdistance` in `tests/test_crash_similarity.py` (one where np.sum(distances) is 0.0 and one where np.sum(distances) is not 0).
