### ISSUE TITLE
Big refactoring [WIP]

### ISSUE THREAD

**Issue by KirillTim** [marco-c/crashsimilarity#68]
- [x] Part 1: Introduce new OOP architecture https://github.com/marco-c/crashsimilarity/pull/66
- [x] Part 2: Add evaluation tool https://github.com/marco-c/crashsimilarity/pull/66
- [ ] Part 3: Rewrite existing WMDistance implementation
- [ ] Part 4: Rewrite CLI
- [ ] Part 5: Remove old code

**Comment by ibrahimsharaf** [comment]
@KirillTim you're skipping part 4 :smile:

**Comment by KirillTim** [comment]
fixed

**Comment by ibrahimsharaf** [comment]
Part 3 is done
