### ISSUE TITLE
Drop python2.7 support

### ISSUE THREAD

**Issue by KirillTim** [marco-c/crashsimilarity#69]
@marco-c, do we really need to support python2.7?
we have already had a [problem](https://travis-ci.org/marco-c/crashsimilarity/jobs/222383557) with CI tests on python2.7
I can't imagine any reason to support both pythons.

**Comment by KirillTim** [comment]
UPD: I use some python3 [features](http://stackoverflow.com/a/31590500), that python2 don't support.

**Comment by marco-c** [comment]
It's fine by me.
We should remove Python 2.7 from the Travis YAML file, so we stop running tests on Python 2.

**Comment by marco-c** [comment]
>  We should remove Python 2.7 from the Travis YAML file, so we stop running tests on Python 2.

We should do this only when we actually break compatibilty, not before.

**Comment by KirillTim** [comment]
OK

**Comment by KirillTim** [comment]
Merged.
