### ISSUE TITLE
Write a function to get a list of stack traces given a signature

### ISSUE THREAD

**Issue by marco-c** [marco-c/crashsimilarity#7]
E.g. using this query: https://crash-stats.mozilla.com/search/?signature=%3DnsDependentCString%3A%3AnsDependentCString&product=Firefox&date=%3E%3D2017-03-03T09%3A52%3A00.000Z&date=%3C2017-03-10T09%3A52%3A00.000Z&_sort=-date&_facets=signature&_facets=proto_signature&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-proto_signature.

Or, directly by using the data that we download to train the model.

**Comment by marco-c** [comment]
> Or, directly by using the data that we download to train the model.

This is already in `get_stack_traces_for_signature`: https://github.com/marco-c/crashsimilarity/blob/e2191a7/crash_similarity.py#L61.

We could add the query part to this function (given that we download the data only for the past few days, the query might give us more stack traces).

**Comment by ibrahimsharaf** [comment]
Do you want to search for 'proto_signature' on the downloaded data locally? or retrieve data from the website using signature? if from the website, are there an API to call?

**Comment by ibrahimsharaf** [comment]
fixed -> https://github.com/marco-c/crashsimilarity/pull/16
