### ISSUE TITLE
Revert Pull Request #84

### ISSUE THREAD

**Issue by KirillTim** [marco-c/crashsimilarity#85]
That was useless refactoring and it break the code somehow.
`StackTracesGetter` is totally useless. This code will be removed. 
Classes hierarchy can't be extended and have to many hardcoded constants and is useless too.
But the main problem is that code just doesn't work.
Lets start Ipython
`ipython   
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.`

and try to import `downloader`

`In [1]: from crashsimilarity import downloader`

```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-83319698043d> in <module>()
----> 1 from crashsimilarity import downloader

/home/kirill/Desktop_hdd/crashsimilarity/crashsimilarity/downloader.py in <module>()
      7 from requests.packages.urllib3 import Retry
      8 
----> 9 from crashsimilarity import utils
     10 
     11 

/home/kirill/Desktop_hdd/crashsimilarity/crashsimilarity/utils.py in <module>()
      6 from smart_open import smart_open
      7 
----> 8 from crashsimilarity.downloader import SocorroDownloader
      9 
     10 

ImportError: cannot import name 'SocorroDownloader'
```
Ooops...

**Comment by marco-c** [comment]
Strange, it is working for me and the tests are passing, so there might be something wrong with your configuration.
Anyway, we can move StackTracesGetter to the downloader module.

The refactoring was not meant to be final, so it doesn't have to be perfect. We can't predict how the code is going to evolve. It's possible we will refactor it even more when we add more different algorithms.

**Comment by KirillTim** [comment]
> Strange, it is working for me and the tests are passing, so there might be something wrong with your configuration.

It is ok with tests on my machine too.
I tried python3.5 and python3.6. With clean setup, just after `git pull`. It is strange, I know. Will investigate later.
