### ISSUE TITLE
Fix download_stack_traces_for_signature

### ISSUE THREAD

**Issue by KirillTim** [marco-c/crashsimilarity#86]
Note for self. 
`^` prefix should be add to signatures request to match only those traces that starts with particular signature, not contains it.

https://github.com/marco-c/crashsimilarity/blob/1362af5df2caac315ffe6f803ddb2cc54305c44b/crashsimilarity/downloader.py#L58

**Comment by marco-c** [comment]
> ^ prefix should be add to signatures request to match only those traces that starts with particular signature, not contains it.

No, `download_stack_traces_for_signature` has to only download the stack traces belonging to that specific signatures (this is what the `=` operator does, it matches a specific string), not all the stack traces from all signatures that start with a specific string (which is what the `^` operator does).

Two signatures that start with the same string can be different than each other, we shouldn't consider them equal.
